# Generated by Django 2.0.10 on 2019-02-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('is_domesticated', models.BooleanField(default=False)),
            ],
        ),
    ]
